import { DisplayColumn, EducationPlanForTerm } from "../../../view-ep/models/education-plan";

export const tableColumns: DisplayColumn[] = [
  {
    name: 'Цикл',
    key: 'cycle'
  },
  {
    name: 'Семестр',
    key: 'term',
  },
  {
    name: 'Навчальна дисципліна',
    key: 'name',
  },
  {
    name: 'Кафедра',
    key: 'department',
  },
  {
    name: 'Лекції',
    key: 'lectures',
  },
  {
    name: 'Практичні',
    key: 'practical',
  },
  {
    name: 'Аудиторні години',
    key: 'classHours',
  },
  {
    name: 'Самостійна робота',
    key: 'selfWork',
  },
  {
    name: 'Всього годин',
    key: 'totalHours',
  },
];

export const educationPlanForTerm: EducationPlanForTerm[] = [
  {
    cycle: 1,
    term: 2,
    name: 'Вища математика',
    department: '503',
    totalHours: 100,
    selfWork: 20,
    classHours: 25,
    practical: 5,
    labs: 30,
    lectures: 40,
    exam: 'exam',
    practical1: 2,
    practical2: 2,
    labs1: 'labs1',
    labs2: 'labs2',
    lectures1: 3,
    lectures2: 1,
    RGR: 'RGR',
    credits: 10,
    delete: 'Delete',
  },
  {
    cycle: 2,
    term: 1,
    name: 'Комп\'ютерні мережі',
    department: '503',
    totalHours: 100,
    selfWork: 20,
    classHours: 25,
    practical: 5,
    labs: 30,
    lectures: 40,
    exam: 'exam',
    practical1: 4,
    practical2: 1,
    labs1: 'labs1',
    labs2: 'labs2',
    lectures1: 1,
    lectures2: 3,
    RGR: 'KP',
    credits: 10,
    delete: 'Delete',
  },
  {
    cycle: 2,
    term: 1,
    name: 'Інженерія ПЗ',
    department: '503',
    totalHours: 100,
    selfWork: 20,
    classHours: 25,
    practical: 5,
    labs: 30,
    lectures: 40,
    exam: 'exam',
    practical1: 4,
    practical2: 1,
    labs1: 'labs1',
    labs2: 'labs2',
    lectures1: 1,
    lectures2: 3,
    RGR: 'KP',
    credits: 10,
    delete: 'Delete',
  },
  {
    cycle: 2,
    term: 1,
    name: 'Надійність та відмовостійкість комп’ютерних систем',
    department: '503',
    totalHours: 100,
    selfWork: 20,
    classHours: 25,
    practical: 5,
    labs: 30,
    lectures: 40,
    exam: 'exam',
    practical1: 4,
    practical2: 1,
    labs1: 'labs1',
    labs2: 'labs2',
    lectures1: 1,
    lectures2: 3,
    RGR: 'KP',
    credits: 10,
    delete: 'Delete',
  },
  {
    cycle: 2,
    term: 1,
    name: 'Проектування вбудованих аерокосмічних систем',
    department: '503',
    totalHours: 100,
    selfWork: 20,
    classHours: 25,
    practical: 5,
    labs: 30,
    lectures: 40,
    exam: 'exam',
    practical1: 4,
    practical2: 1,
    labs1: 'labs1',
    labs2: 'labs2',
    lectures1: 1,
    lectures2: 3,
    RGR: 'KP',
    credits: 10,
    delete: 'Delete',
  },
  {
    cycle: 2,
    term: 1,
    name: 'Паралел. та розподіл. обчисл.',
    department: '503',
    totalHours: 100,
    selfWork: 20,
    classHours: 25,
    practical: 5,
    labs: 30,
    lectures: 40,
    exam: 'exam',
    practical1: 4,
    practical2: 1,
    labs1: 'labs1',
    labs2: 'labs2',
    lectures1: 1,
    lectures2: 3,
    RGR: 'KP',
    credits: 10,
    delete: 'Delete',
  }
];

export const educationPlan: EducationPlanForTerm[][] = [
  educationPlanForTerm,
  educationPlanForTerm,
  educationPlanForTerm,
  educationPlanForTerm,
  educationPlanForTerm,
  educationPlanForTerm,
]